USE `nustour_db`;
CREATE TABLE IF NOT EXISTS `building` (
--  name          type            constraints
    `id`          INT             NOT NULL      AUTO_INCREMENT,
    `name`        VARCHAR(32)     NOT NULL      UNIQUE,
    `location`    VARCHAR(256)    NOT NULL      ,
    `area`        VARCHAR(128)    NOT NULL      ,
    `tel`         VARCHAR(32)     NOT NULL      ,
    `fax`         VARCHAR(32)     NOT NULL      ,
    
    PRIMARY KEY (`id`)
);
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Office of Admissions", "2 College Avenue West, University Town #01-03 (S) 138607", "University Town", "+65 6516 1010", "+65 6778 7570", "/building/location/Office+of+Admissions.png", "/building/image/Office+of+Admissions.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Office of Alumni Relations", "11 Kent Ridge Drive, Shaw Foundation Alumni House (S) 119244", "Kent Ridge Campus", "+65 6516 5775", "+65 6464 1498", "/building/location/Office+of+Alumni+Relations.png", "/building/image/Office+of+Alumni+Relations.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Office of Campus Amenities", "8 Kent Ridge Drive, #02-01 (S) 119246", "Ventus (University Campus Infrastructure)", "", "", "/building/location/Office+of+Campus+Amenities.png", "/building/image/Office+of+Campus+Amenities.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Office of Financial Services", "21 Lower Kent Ridge Road, University Hall, Tan Chin Tuan Wing #03-02 (S) 119077", "Kent Ridge Campus", "+65 6516 1981", "+65 6778 6570", "/building/location/Office+of+Financial+Services.png", "/building/image/Office+of+Financial+Services.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Office of Human Resources", "University Hall Tan Chin Tuan Wing, #04-01, 21 Lower Kent Ridge Road (S) 119077", "Kent Ridge Campus", "+65 6516 2331", "+65 6778 3948", "/building/location/Office+of+Human+Resources.png", "/building/image/Office+of+Human+Resources.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Office of Housing Services", "10 Kent Ridge Crescent, Block ADM Level 3 (S) 119260", "Kent Ridge Campus", "+65 6516 3697", "+65 6777 3840", "/building/location/Office+of+Housing+Services.png", "/building/image/Office+of+Housing+Services.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Information Technology", "2 Engineering Drive 4 (S) 117584", "Kent Ridge Campus", "+65 6516 2080", "+65 6516 7210", "/building/location/Information+Technology.png", "/building/image/Information+Technology.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("NUS Entrepreneurship Centre", "21 Heng Mui Keng Terrace, I3 Building Level 5 (S) 119613", "Kent Ridge Campus", "+65 6777 6990", "", "/building/location/NUS+Entrepreneurship+Centre.png", "/building/image/NUS+Entrepreneurship+Centre.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("C J Koh Law Library", "469D Bukit Timah Road (S) 259773", "Bukit Timah Campus", "+65 6516 2043", "+65 6468 3407", "/building/location/C+J+Koh+Law+Library.png", "/building/image/C+J+Koh+Law+Library.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Central Library", "12 Kent Ridge Crescent (S) 119275", "Kent Ridge Campus", "+65 6516 2028", "+65 6777 3571", "/building/location/Central+Library.png", "/building/image/Central+Library.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Chinese Library", "12 Kent Ridge Crescent (S) 119275", "Kent Ridge Campus", "+65 6516 2028", "+65 6777 3571", "/building/location/Chinese+Library.png", "/building/image/Chinese+Library.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Hon Sui Sen Memorial Library", "1 Hon Sui Sen Drive (S) 117588", "Kent Ridge Campus", "+65 6516 3131", "+65 6778 6301", "/building/location/Hon+Sui+Sen+Memorial+Library.png", "/building/image/Hon+Sui+Sen+Memorial+Library.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Medical Library", "Centre for Translational Medicine, Block MD6, 14 Medical Drive, #05-01 (S) 117599", "Kent Ridge Campus", "+65 6516 2046", "+65 6773 6574", "/building/location/Medical+Library.png", "/building/image/Medical+Library.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Music Library", "3 Conservatory Drive (S) 117376", "Kent Ridge Campus", "+65 6516 8130", "+65 6778 9849", "/building/location/Music+Library.png", "/building/image/Music+Library.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Science Library", "10 Science Drive 2, Block S6 Level 4 (S) 117548", "Kent Ridge Campus", "+65 6516 2454", "+65 6778 6118", "/building/location/Science+Library.png", "/building/image/Science+Library.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("NUS Museum", "University Cultural Centre, 50 Kent Ridge Crescent (S) 119279", "Kent Ridge Campus", "+65 6516 8817", "+65 6778 3738", "/building/location/NUS+Museum.png", "/building/image/NUS+Museum.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Student Service Centre", "31 Lower Kent Ridge Road, Yusof Ishak House Level 1 (S) 119078", "Kent Ridge Campus", "+65 6516 1177", "+65 6777 0155", "/building/location/Student+Service+Centre.png", "/building/image/Student+Service+Centre.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("University Health Centre", "20 Lower Kent Ridge Road, University Health Centre (S) 119080", "Kent Ridge Campus", "+65 6776 1631", "+65 6778 3173", "/building/location/University+Health+Centre.png", "/building/image/University+Health+Centre.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Eusoff Hall", "10 Kent Ridge Drive (S) 119242", "Kent Ridge Campus", "", "", "/building/location/Eusoff+Hall.png", "/building/image/Eusoff+Hall.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Kent Ridge Hall", "10 Heng Mui Keng Terrace (S) 119617", "Kent Ridge Campus", "", "", "/building/location/Kent+Ridge+Hall.png", "/building/image/Kent+Ridge+Hall.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("King Edward VII Hall", "1A Kent Ridge Road (S) 119224", "Kent Ridge Campus", "", "", "/building/location/King+Edward+VII+Hall.png", "/building/image/King+Edward+VII+Hall.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Prince George's Park Residences", "27 Prince George's Park Road (S) 118425", "Kent Ridge Campus", "+65 6601 1111", "+65 6778 2050", "/building/location/Prince+George's+Park+Residences.png", "/building/image/Prince+George's+Park+Residences.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Raffles Hall", "19 Kent Ridge Crescent (S) 119278", "Kent Ridge Campus", "", "", "/building/location/Raffles+Hall.png", "/building/image/Raffles+Hall.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Sheares Hall", "20 Heng Mui Keng Terrace (S) 119618", "Kent Ridge Campus", "", "", "/building/location/Sheares+Hall.png", "/building/image/Sheares+Hall.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("Temasek Hall", "12 Kent Ridge Drive (S) 119243", "Kent Ridge Campus", "", "", "/building/location/Temasek+Hall.png", "/building/image/Temasek+Hall.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("UTown Residence", "36 College Avenue East (S) 138600", "Kent Ridge - UTOWN Campus", "", "", "/building/location/UTown+Residence.png", "/building/image/UTown+Residence.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("FoS", "FoS", "Kent Ridge Campus", "", "", "/building/location/FoS.png", "/building/image/FoS.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("SoC", "SoC", "Kent Ridge Campus", "", "", "/building/location/SoC.png", "/building/image/SoC.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("FASS", "FASS", "Kent Ridge Campus", "", "", "/building/location/FASS.png", "/building/image/FASS.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("BIZ", "BIZ", "Kent Ridge Campus", "", "", "/building/location/BIZ.png", "/building/image/BIZ.jpg");
INSERT INTO `building` (`name`, `location`, `area`, `tel`, `fax`, `locationUrl`, `imageUrl`) VALUES ("FoE", "FoE", "Kent Ridge Campus", "", "", "/building/location/FoE.png", "/building/image/FoE.jpg");